language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

install:
  - sudo apt-get install parallel
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/coverage
  - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php

script:
  # Run tests for the various components in parallel
  - ls -d tests/ZendTest/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/phpunit.xml.dist --coverage-php build/coverage/coverage-{/.}.cov {};' || exit 1
  # Run coding standard checks in parallel
  - ls -d library/Zend/* tests/ZendTest/* bin | parallel --gnu --keep-order 'echo "Running {} CS checks"; ./vendor/bin/php-cs-fixer fix {} -v --diff --dry-run --config-file=.php_cs;' || exit 1

after_script:
  # Merges the individual clover reports of each component into a single clover.xml
  - php vendor/bin/phpcov merge --clover build/logs/clover.xml build/coverage
  - php vendor/bin/coveralls

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
