<?php
return '
{
    "transport":"POST",
    "envelope":"JSON-RPC-1.0",
    "contentType":"application/json",
    "SMDVersion":"2.0",
    "services":{
        "add":{
            "envelope":"JSON-RPC-1.0",
            "transport":"POST",
            "parameters":[
                {
                    "type":"integer",
                    "name":"a",
                    "optional":false
                },
                {
                    "type":"integer",
                    "name":"b",
                    "optional":false
                }
            ],
            "returns":"integer"
        },
        "concat":{
            "envelope":"JSON-RPC-1.0",
            "transport":"POST",
            "parameters":[
                {
                    "type":"string",
                    "name":"a",
                    "optional":false
                },
                {
                    "type":"string",
                    "name":"b",
                    "optional":false
                }
            ],
            "returns":"string"
        }
   },
   "methods":{
        "add":{
            "envelope":"JSON-RPC-1.0",
            "transport":"POST",
            "parameters":[
                {
                    "type":"integer",
                    "name":"a",
                    "optional":false
                },
                {
                    "type":"integer",
                    "name":"b",
                    "optional":false
                }
            ],
            "returns":"integer"
        },
        "concat":{
            "envelope":"JSON-RPC-1.0",
            "transport":"POST",
            "parameters":[
                {
                    "type":"string",
                    "name":"a",
                    "optional":false
                },
                {
                    "type":"string",
                    "name":"b",
                    "optional":false
                }
            ],
            "returns":"string"
        }
    }
}
';